with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
issue-845-fix: true
packages:
  github.com/ksysoev/help-my-pet/pkg/core:
    interfaces:
      LLM:
  github.com/ksysoev/help-my-pet/pkg/bot:
    interfaces:
      AIProvider:
      BotAPI:
  github.com/ksysoev/help-my-pet/pkg/cmd:
    interfaces:
      BotService:
