with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
issue-845-fix: true
packages:
  github.com/ksysoev/help-my-pet/pkg/prov/anthropic:
    interfaces:
      Model:
  github.com/ksysoev/help-my-pet/pkg/core:
    interfaces:
      ConversationRepository:
      LLM:
      RateLimiter:
      AIService:
      PetProfileRepository:
      Conversation:
  github.com/ksysoev/help-my-pet/pkg/bot:
    interfaces:
      BotAPI:
      RateLimiter:
      AIProvider:
      httpClient:
  github.com/ksysoev/help-my-pet/pkg/cmd:
    interfaces:
      BotService:
