// Code generated by mockery v2.50.4. DO NOT EDIT.

//go:build !compile

package bot

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAIProvider is an autogenerated mock type for the AIProvider type
type MockAIProvider struct {
	mock.Mock
}

type MockAIProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIProvider) EXPECT() *MockAIProvider_Expecter {
	return &MockAIProvider_Expecter{mock: &_m.Mock}
}

// GetPetAdvice provides a mock function with given fields: ctx, chatID, question
func (_m *MockAIProvider) GetPetAdvice(ctx context.Context, chatID string, question string) (string, error) {
	ret := _m.Called(ctx, chatID, question)

	if len(ret) == 0 {
		panic("no return value specified for GetPetAdvice")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, chatID, question)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, chatID, question)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, chatID, question)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_GetPetAdvice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetAdvice'
type MockAIProvider_GetPetAdvice_Call struct {
	*mock.Call
}

// GetPetAdvice is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - question string
func (_e *MockAIProvider_Expecter) GetPetAdvice(ctx interface{}, chatID interface{}, question interface{}) *MockAIProvider_GetPetAdvice_Call {
	return &MockAIProvider_GetPetAdvice_Call{Call: _e.mock.On("GetPetAdvice", ctx, chatID, question)}
}

func (_c *MockAIProvider_GetPetAdvice_Call) Run(run func(ctx context.Context, chatID string, question string)) *MockAIProvider_GetPetAdvice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAIProvider_GetPetAdvice_Call) Return(_a0 string, _a1 error) *MockAIProvider_GetPetAdvice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_GetPetAdvice_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAIProvider_GetPetAdvice_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockAIProvider) Start(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockAIProvider_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAIProvider_Expecter) Start(ctx interface{}) *MockAIProvider_Start_Call {
	return &MockAIProvider_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockAIProvider_Start_Call) Run(run func(ctx context.Context)) *MockAIProvider_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAIProvider_Start_Call) Return(_a0 string, _a1 error) *MockAIProvider_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_Start_Call) RunAndReturn(run func(context.Context) (string, error)) *MockAIProvider_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIProvider creates a new instance of MockAIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIProvider {
	mock := &MockAIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
