// Code generated by mockery v2.50.4. DO NOT EDIT.

//go:build !compile

package bot

import (
	context "context"

	core "github.com/ksysoev/help-my-pet/pkg/core"
	mock "github.com/stretchr/testify/mock"
)

// MockAIProvider is an autogenerated mock type for the AIProvider type
type MockAIProvider struct {
	mock.Mock
}

type MockAIProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIProvider) EXPECT() *MockAIProvider_Expecter {
	return &MockAIProvider_Expecter{mock: &_m.Mock}
}

// ProcessEditProfile provides a mock function with given fields: ctx, request
func (_m *MockAIProvider) ProcessEditProfile(ctx context.Context, request *core.UserMessage) (*core.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ProcessEditProfile")
	}

	var r0 *core.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.UserMessage) (*core.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.UserMessage) *core.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.UserMessage) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_ProcessEditProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessEditProfile'
type MockAIProvider_ProcessEditProfile_Call struct {
	*mock.Call
}

// ProcessEditProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.UserMessage
func (_e *MockAIProvider_Expecter) ProcessEditProfile(ctx interface{}, request interface{}) *MockAIProvider_ProcessEditProfile_Call {
	return &MockAIProvider_ProcessEditProfile_Call{Call: _e.mock.On("ProcessEditProfile", ctx, request)}
}

func (_c *MockAIProvider_ProcessEditProfile_Call) Run(run func(ctx context.Context, request *core.UserMessage)) *MockAIProvider_ProcessEditProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.UserMessage))
	})
	return _c
}

func (_c *MockAIProvider_ProcessEditProfile_Call) Return(_a0 *core.Response, _a1 error) *MockAIProvider_ProcessEditProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_ProcessEditProfile_Call) RunAndReturn(run func(context.Context, *core.UserMessage) (*core.Response, error)) *MockAIProvider_ProcessEditProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessMessage provides a mock function with given fields: ctx, request
func (_m *MockAIProvider) ProcessMessage(ctx context.Context, request *core.UserMessage) (*core.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMessage")
	}

	var r0 *core.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.UserMessage) (*core.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.UserMessage) *core.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.UserMessage) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_ProcessMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMessage'
type MockAIProvider_ProcessMessage_Call struct {
	*mock.Call
}

// ProcessMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.UserMessage
func (_e *MockAIProvider_Expecter) ProcessMessage(ctx interface{}, request interface{}) *MockAIProvider_ProcessMessage_Call {
	return &MockAIProvider_ProcessMessage_Call{Call: _e.mock.On("ProcessMessage", ctx, request)}
}

func (_c *MockAIProvider_ProcessMessage_Call) Run(run func(ctx context.Context, request *core.UserMessage)) *MockAIProvider_ProcessMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.UserMessage))
	})
	return _c
}

func (_c *MockAIProvider_ProcessMessage_Call) Return(_a0 *core.Response, _a1 error) *MockAIProvider_ProcessMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_ProcessMessage_Call) RunAndReturn(run func(context.Context, *core.UserMessage) (*core.Response, error)) *MockAIProvider_ProcessMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIProvider creates a new instance of MockAIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIProvider {
	mock := &MockAIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
