// Code generated by mockery v2.50.4. DO NOT EDIT.

//go:build !compile

package bot

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockhttpClient is an autogenerated mock type for the httpClient type
type MockhttpClient struct {
	mock.Mock
}

type MockhttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockhttpClient) EXPECT() *MockhttpClient_Expecter {
	return &MockhttpClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: url
func (_m *MockhttpClient) Get(url string) (*http.Response, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Response, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockhttpClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *MockhttpClient_Expecter) Get(url interface{}) *MockhttpClient_Get_Call {
	return &MockhttpClient_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *MockhttpClient_Get_Call) Run(run func(url string)) *MockhttpClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockhttpClient_Get_Call) Return(_a0 *http.Response, _a1 error) *MockhttpClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpClient_Get_Call) RunAndReturn(run func(string) (*http.Response, error)) *MockhttpClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhttpClient creates a new instance of MockhttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockhttpClient {
	mock := &MockhttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
