// Code generated by mockery v2.50.4. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	llms "github.com/tmc/langchaingo/llms"
)

// MockLLM is an autogenerated mock type for the LLM type
type MockLLM struct {
	mock.Mock
}

type MockLLM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLM) EXPECT() *MockLLM_Expecter {
	return &MockLLM_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, prompt, options
func (_m *MockLLM) Call(ctx context.Context, prompt string, options ...llms.CallOption) (*Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, prompt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...llms.CallOption) (*Response, error)); ok {
		return rf(ctx, prompt, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...llms.CallOption) *Response); ok {
		r0 = rf(ctx, prompt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...llms.CallOption) error); ok {
		r1 = rf(ctx, prompt, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLM_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockLLM_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - options ...llms.CallOption
func (_e *MockLLM_Expecter) Call(ctx interface{}, prompt interface{}, options ...interface{}) *MockLLM_Call_Call {
	return &MockLLM_Call_Call{Call: _e.mock.On("Call",
		append([]interface{}{ctx, prompt}, options...)...)}
}

func (_c *MockLLM_Call_Call) Run(run func(ctx context.Context, prompt string, options ...llms.CallOption)) *MockLLM_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]llms.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(llms.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLLM_Call_Call) Return(_a0 *Response, _a1 error) *MockLLM_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLM_Call_Call) RunAndReturn(run func(context.Context, string, ...llms.CallOption) (*Response, error)) *MockLLM_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLM creates a new instance of MockLLM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLM {
	mock := &MockLLM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
